### ISSUE TITLE
On "AllowedRoles" change make sure "PreselectRole" is re-populated.

### ISSUE THREAD

**Issue by iiminov** [DNN-Connect/UserAccountManagement#10]
If I uncheck ```All Roles``` in module settings I get the following error
```A critical error has occurred. Object reference not set to an instance of an object.```
Something to do with list of allowed roles.!?

I was trying to figure out what ```Allowed roles``` was about.
From my understanding it is to do with which roles will appear underneath search bar rather then permissions (we have a whole Permissions tab for that).

I suppose this doesn't work. Because as soon as I uncheck ```All Roles``` I get an error. And the error log as follows:

```
AssemblyVersion:7.3.1
PortalID:0
PortalName:Delta Centre Web Application
UserID:9
UserName:isa
ActiveTabID:139
ActiveTabName:Edit Residents
RawURL:/Resident/Edit-Residents
AbsoluteURL:/Default.aspx
AbsoluteURLReferrer:https://app.deltacentre.org/Resident/Edit-Residents/ctl/Module/ModuleId/576/content/0?ReturnURL=/Default.aspx?tabid=139&error=Object+reference+not+set+to+an+instance+of+an+object.&popUp=true
UserAgent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:9d5b1edf-0efe-4406-bb44-ba38a3517562
InnerException:Unhandled Error Adding Module to ContentPane
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:System.Threading.Thread.AbortInternal
StackTrace:
Message:
DotNetNuke.Services.Exceptions.ModuleLoadException: Unhandled Error Adding Module to ContentPane ---> System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.End()
   at Connect.Modules.UserManagement.AccountManagement.View.Page_Init(Object sender, EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
   at System.Web.UI.Control.EnsureChildControls()
   at DotNetNuke.UI.Containers.Container.get_ModuleControl()
   at DotNetNuke.UI.Containers.Container.ProcessModule()
   at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
   --- End of inner exception stack trace ---
   at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
   at DotNetNuke.UI.Skins.Skin.InjectModule(Pane pane, ModuleInfo module)
Source:
Server Name: server1
```

Not really sure what could be causing this. My few ideas:
1. ```uid``` not part of of a role selected in ```Allowed roles``` but I check with SuperAdmin and normal user account whic is part of selected role and still get error message.
2. Version of DNN 7.3.1
3. me - trying to do something unnecessary

**Comment by peppertree** [comment]
For now please work around as suggested above. We'll fix this in the next major release that also adds a complete new UI.
