### ISSUE TITLE
Errors after making edits/changes to module, skin settings and etc.

### ISSUE THREAD

**Issue by gmonostudio** [DNN-Connect/UserAccountManagement#16]
Greetings Philipp Becker, First I want to thank you for this module, it is an awesome product and excellent solution for us. We are writing to inform you of some of the errors we are receiving when making any edits/changes to the module. We recently installed your module to a newly installed site (not live yet). We removed the actual url location from the error messages for privacy. We were able to get it working to perform some of its design functions, such as deleting groups that a user belongs to and setting viewer permissions to non-admins-- Those functions worked find. We were not able to get the search to work as indicated by other users. Please review some of the error reports and advise us on what we should do. Thank you!
----------------------------------------------------------------------
AssemblyVersion:7.3.1
PortalID:0
PortalName:My Site 
UserID:5
UserName:My Site 
ActiveTabID:108
ActiveTabName:User Manager
RawURL:/User-Manager
AbsoluteURL:/Default.aspx
AbsoluteURLReferrer:http://mysite.info/Control-Panel
UserAgent:Mozilla/5.0 (Windows NT 5.1; rv:32.0) Gecko/20100101 Firefox/32.0
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:6a595087-25c1-4753-ae8b-a987c3edc23b
InnerException:Conversion from string "" to type 'Integer' is not valid.
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble
StackTrace:
Message:
DotNetNuke.Services.Exceptions.PageLoadException: Conversion from string "" to type 'Integer' is not valid. ---> System.InvalidCastException: Conversion from string "" to type 'Integer' is not valid. ---> System.FormatException: Input string was not in a correct format.
at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
--- End of inner exception stack trace ---
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(Object Value)
at Connect.Modules.UserManagement.AccountManagement.View.BindRoles()
at Connect.Modules.UserManagement.AccountManagement.View.Page_Load(Object sender, EventArgs e)
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
--- End of inner exception stack trace ---
Source:
Server Name: vps01
9/25/2014 3:25:19 PMGeneral Exception My Site _ My Site AssemblyVersion 7.3.1 PortalID 0 PortalName My Site 
AssemblyVersion:7.3.1
PortalID:0
PortalName:My Site 
UserID:5
UserName:My Site
ActiveTabID:108
ActiveTabName:User Manager
RawURL:/User-Manager
AbsoluteURL:/Default.aspx
AbsoluteURLReferrer:http://mysite.info/Control-Panel
UserAgent:Mozilla/5.0 (Windows NT 5.1; rv:32.0) Gecko/20100101 Firefox/32.0
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:90c57c50-f767-4f96-927a-590d3480012e
InnerException:Unhandled Error Adding Module to ContentPane
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble
StackTrace:
Message:
DotNetNuke.Services.Exceptions.ModuleLoadException: Unhandled Error Adding Module to ContentPane ---> System.InvalidCastException: Conversion from string "" to type 'Integer' is not valid. ---> System.FormatException: Input string was not in a correct format.
at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
--- End of inner exception stack trace ---
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(Object Value)
at Connect.Modules.UserManagement.AccountManagement.View.Page_Init(Object sender, EventArgs e)
at System.Web.UI.Control.InitRecursive(Control namingContainer)
at System.Web.UI.Control.AddedControl(Control control, Int32 index)
at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
at System.Web.UI.Control.EnsureChildControls()
at DotNetNuke.UI.Containers.Container.get_ModuleControl()
at DotNetNuke.UI.Containers.Container.ProcessModule()
at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
--- End of inner exception stack trace ---
at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
at DotNetNuke.UI.Skins.Skin.InjectModule(Pane pane, ModuleInfo module)
Source:
Server Name: vps01
9/25/2014 3:25:19 PMGeneral Exception My Site AssemblyVersion 7.3.1 PortalID 0 PortalName My Site 
AssemblyVersion:7.3.1
PortalID:0
PortalName:My Site
UserID:5
UserName:My Site 
ActiveTabID:108
ActiveTabName:User Manager
RawURL:/User-Manager
AbsoluteURL:/Default.aspx
AbsoluteURLReferrer:http://mysite.info/Control-Panel
UserAgent:Mozilla/5.0 (Windows NT 5.1; rv:32.0) Gecko/20100101 Firefox/32.0
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:cfeaecc5-3d6d-4d34-8251-c15d34916449
InnerException:Conversion from string "" to type 'Integer' is not valid.
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble
StackTrace:
Message:
System.InvalidCastException: Conversion from string "" to type 'Integer' is not valid. ---> System.FormatException: Input string was not in a correct format.
at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
--- End of inner exception stack trace ---
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(Object Value)
at Connect.Modules.UserManagement.AccountManagement.View.Page_Init(Object sender, EventArgs e)
at System.Web.UI.Control.InitRecursive(Control namingContainer)
at System.Web.UI.Control.AddedControl(Control control, Int32 index)
at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
at System.Web.UI.Control.EnsureChildControls()
at DotNetNuke.UI.Containers.Container.get_ModuleControl()
at DotNetNuke.UI.Containers.Container.ProcessModule()
at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
Source:
Server Name: vps01
9/25/2014 3:25:14 PMPage Load Exception My Site My Site  AssemblyVersion 7.3.1 PortalID 0 PortalName My Site 
AssemblyVersion:7.3.1
PortalID:0
PortalName:My Site
UserID:5
UserName:My Site 
ActiveTabID:108
ActiveTabName:User Manager
RawURL:/User-Manager
AbsoluteURL:/Default.aspx
AbsoluteURLReferrer:http://mysite.info/User-Manager/RoleId/12
UserAgent:Mozilla/5.0 (Windows NT 5.1; rv:32.0) Gecko/20100101 Firefox/32.0
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:655bbc96-a329-4b27-8548-7e4845e9374e
InnerException:Conversion from string "" to type 'Integer' is not valid.
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble
StackTrace:
Message:
DotNetNuke.Services.Exceptions.PageLoadException: Conversion from string "" to type 'Integer' is not valid. ---> System.InvalidCastException: Conversion from string "" to type 'Integer' is not valid. ---> System.FormatException: Input string was not in a correct format.
at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
--- End of inner exception stack trace ---
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(Object Value)
at Connect.Modules.UserManagement.AccountManagement.View.BindRoles()
at Connect.Modules.UserManagement.AccountManagement.View.Page_Load(Object sender, EventArgs e)
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
--- End of inner exception stack trace ---
Source:
Server Name: vps01
9/25/2014 3:25:14 PMGeneral Exception My Site _ My Site AssemblyVersion 7.3.1 PortalID 0 PortalName My Site 
AssemblyVersion:7.3.1
PortalID:0
PortalName:My Site 
UserID:5
UserName:My Site 
ActiveTabID:108
ActiveTabName:User Manager
RawURL:/User-Manager
AbsoluteURL:/Default.aspx
AbsoluteURLReferrer:http://mysite.info/User-Manager/RoleId/12
UserAgent:Mozilla/5.0 (Windows NT 5.1; rv:32.0) Gecko/20100101 Firefox/32.0
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:dd993c68-14a8-4a7b-a5bb-ca2b276ab834
InnerException:Unhandled Error Adding Module to ContentPane
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble
StackTrace:
Message:
DotNetNuke.Services.Exceptions.ModuleLoadException: Unhandled Error Adding Module to ContentPane ---> System.InvalidCastException: Conversion from string "" to type 'Integer' is not valid. ---> System.FormatException: Input string was not in a correct format.
at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
--- End of inner exception stack trace ---
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(Object Value)
at Connect.Modules.UserManagement.AccountManagement.View.Page_Init(Object sender, EventArgs e)
at System.Web.UI.Control.InitRecursive(Control namingContainer)
at System.Web.UI.Control.AddedControl(Control control, Int32 index)
at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
at System.Web.UI.Control.EnsureChildControls()
at DotNetNuke.UI.Containers.Container.get_ModuleControl()
at DotNetNuke.UI.Containers.Container.ProcessModule()
at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
--- End of inner exception stack trace ---
at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
at DotNetNuke.UI.Skins.Skin.InjectModule(Pane pane, ModuleInfo module)
Source:
Server Name: vps01
9/25/2014 3:25:14 PMGeneral Exception My Site My Site AssemblyVersion 7.3.1 PortalID 0 PortalName My Site 
AssemblyVersion:7.3.1
PortalID:0
PortalName:My Site
UserID:5
UserName:My Site 
ActiveTabID:108
ActiveTabName:User Manager
RawURL:/User-Manager
AbsoluteURL:/Default.aspx
AbsoluteURLReferrer:http://mysite.info/User-Manager/RoleId/12
UserAgent:Mozilla/5.0 (Windows NT 5.1; rv:32.0) Gecko/20100101 Firefox/32.0
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:17665b94-4458-437d-b01e-7b15463b6568
InnerException:Conversion from string "" to type 'Integer' is not valid.
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble
StackTrace:
Message:
System.InvalidCastException: Conversion from string "" to type 'Integer' is not valid. ---> System.FormatException: Input string was not in a correct format.
at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
--- End of inner exception stack trace ---
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(String Value)
at Microsoft.VisualBasic.CompilerServices.Conversions.ToInteger(Object Value)
at Connect.Modules.UserManagement.AccountManagement.View.Page_Init(Object sender, EventArgs e)
at System.Web.UI.Control.InitRecursive(Control namingContainer)
at System.Web.UI.Control.AddedControl(Control control, Int32 index)
at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
at System.Web.UI.Control.EnsureChildControls()
at DotNetNuke.UI.Containers.Container.get_ModuleControl()
at DotNetNuke.UI.Containers.Container.ProcessModule()
at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
Source:
Server Name: vps01

**Comment by peppertree** [comment]
This should be fixed in 7.3.0
