### ISSUE TITLE
Error after adding, deleting and restoring a user

### ISSUE THREAD

**Issue by tdgarvey** [DNN-Connect/UserAccountManagement#37]
AssemblyVersion:7.3.2
PortalID:0
PortalName:Johnson Bank
UserID:315
UserName:testsuper
ActiveTabID:112
ActiveTabName:Admin Users
RawURL:/Administration/Admin-Users/RoleId/2
AbsoluteURL:/Default.aspx
AbsoluteURLReferrer:http://jiforms.thegarveygroup.com/Administration/Admin-Users/RoleId/2
UserAgent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:41.0) Gecko/20100101 Firefox/41.0
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:1b009802-0684-4b91-ae60-a1b641e62ff4
InnerException:# is not a valid value for Int32.
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:System.ParseNumbers.StringToInt
StackTrace:
Message:
DotNetNuke.Services.Exceptions.PageLoadException: # is not a valid value for Int32. ---> System.Exception: # is not a valid value for Int32. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToInt32(String value, Int32 fromBase)
   at System.ComponentModel.Int32Converter.FromString(String value, Int32 radix)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Drawing.ColorConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.Drawing.ColorTranslator.FromHtml(String htmlColor)
   at ASP.portals__default_skins_lightness_indexrevindex_ascx.HexToRGBA(String hex, String alpha)
   at ASP.portals__default_skins_lightness_indexrevindex_ascx.__Render__control1(HtmlTextWriter __w, Control parameterContainer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderChildren(HtmlTextWriter writer)
   at System.Web.UI.Control.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderChildren(HtmlTextWriter writer)
   at System.Web.UI.Control.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.HtmlControls.HtmlForm.RenderChildren(HtmlTextWriter writer)
   at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer)
   at System.Web.UI.HtmlControls.HtmlForm.Render(HtmlTextWriter output)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.HtmlControls.HtmlForm.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderChildren(HtmlTextWriter writer)
   at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderChildren(HtmlTextWriter writer)
   at DotNetNuke.Framework.PageBase.Render(HtmlTextWriter writer)
   at DotNetNuke.Framework.DefaultPage.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   --- End of inner exception stack trace ---
Source:
Server Name: RD000D3A603587

**Comment by tdgarvey** [comment]
I receive this page load exception error only when a non admin user performs a action. The action completes and then the page load exception generates. Could this just be the nature of the DNN roles and your extension?

**Comment by tbello1** [comment]
tdgarvey, were you able to resolve the cause of this error? I am getting the same error under the same circumstances. Thanks.

**Comment by tdgarvey** [comment]
tbello1 - From what I remember I don't think the extension ever worked properly. The site is long since shut down so I cannot go and see. Are you using the same skin as I was? I am not sure if the error was coming from the skin or if it never worked no matter what.
